export const COURSE_QUERY_HEADLINE='COURSE_QUERY_HEADLINE';

export const ASK_QUERY_LIST='ASK_QUERY_LIST';


export const MY_LOGIN_FLAG='MY_LOGIN_FLAG';

export const MY_LOGIN_INFO='MY_LOGIN_INFO';

export const ASK_LISTITEM_DETAIL='ASK_LISTITEM_DETAIL';


