export const COURSE_QUERY_HEADLINE='COURSE_QUERY_HEADLINE';

export const ASK_QUERY_LIST='ASK_QUERY_LIST';

<<<<<<< HEAD
export const MY_LOGIN_FLAG='MY_LOGIN_FLAG';

export const MY_LOGIN_INFO='MY_LOGIN_INFO';
=======
export const ASK_LISTITEM_DETAIL='ASK_LISTITEM_DETAIL';
>>>>>>> 9a60eab1094df6ba129f6514672d33d551bbbb87
